server:
  port: ${PORT:8083}
  servlet:
    context-path: /catalog

eureka:
  client:
    service-url:  
      defaultZone: http://localhost:8761/eureka/

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

queue:
  name: movies