
server:
  port: ${PORT:8082}
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aloisiot/backend_avaliacao_1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  name: Actuator informação
  author: Teste
  severity: Medio